server:
  port: 8080

services:
  auth:
    base-url: http://localhost:8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auction-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auctions/**

            - id: bidding-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/bids/**

            - id: auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083

authorization:
  rules:
    - method: POST
      path: /api/auctions
      roles:
        - ADMIN

    - method: PATCH
      path: /api/auctions/*/activate
      roles:
        - ADMIN

    - method: PATCH
      path: /api/auctions/*/cancel
      roles:
        - ADMIN

    - method: PATCH
      path: /api/auctions/*/finish
      roles:
        - ADMIN

    - method: GET
      path: api/auctions/**
      roles:
        - ADMIN
        - BIDDER

    - method: POST
      path: /api/bids/**
      roles:
        - ADMIN
        - BIDDER

    - method: GET
      path: /api/bids/**
      roles:
        - ADMIN
        - BIDDER